name: animated_styled_widget
description: Lets you use a serializable style to make customizable and animated widgets.
version: 0.2.8
homepage: https://github.com/KevinVan720/animated_styled_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dimension: ^0.1.5

  flutter_class_parser: ^0.2.3

  morphable_shape: ^1.5.0

  tuple: ^2.0.0

  provider: ^5.0.0

  simple_animations: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

