name: animated_styled_widget
description: Lets you use a serializable style to make customizable and animated widgets.
version: 0.5.0
homepage: https://github.com/KevinVan720/animated_styled_widget

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  dimension: ^0.2.0

  flutter_class_parser: ^0.2.5

  morphable_shape: ^2.0.0

  tuple: ^2.0.0

  provider: ^6.0.5

  simple_animations: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

